alkemyTech/OT225-server

migrations/20220616004328-create-activities.js, models/activities.js, seeders/20220616010104-demo-activity.js
- Model activities added
- Migration activities added
- Base controller activities added
- Seeder Activities added
=> Create Model, Migration, Controller & Seeder for Activities

migrations/20220619112921-create-categories.js, models/categories.js
- Model categories added
- Migration categories added
- Base controller categories added
=> Categories model

app.js, controllers/categories/index.js, migrations/20220619112921-create-categories.js, models/categories.js, routes/categories.js
- Created controller to list categories
- Created route to list categories
=> Listado categories

migrations/20220616004328-create-activities.js, models/activities.js
- add jsdocs to activities migration
- add jsdocs to activities model
=> Update migration/model activities with jsdoc

controllers/categories.js, controllers/news.js, routes/categories.js, routes/news.js
hice el updateNews y corregí un problema de importación del controller y ruta categoría
=> endpoint updateNews 

app.js, controllers/categories.js, routes/categories.js
- Added get category details controller
- Added route for get the details of a category (by id)
- Fixed the use of the categories route in app.js (it was duplicated)
- Fixed status of the error code in the details category controller
- Added jsdocs for controller
=> Category Details Controller

controllers/activity.js, controllers/categories.js, migrations/20220701211616-create-slides.js, models/slides.js, package.json, routes/activities.js, seeders/20220701215420-demo-slides.js
- Create Slides Model
- Create Slides Migration
- Associate Slides with Organizations
=> Slides Model & Migration

app.js, config/aws.js, controllers/slides.js, migrations/20220701211616-create-slides.js, models/slides.js, package.json, routes/slides.js, utils/images.js
- Add & configure AWS for use S3 Bucket
- Add an util to upload images to S3
- Add soft delete to Slides Model
- Add Slides Controllers: Create / Update / Delete / GetAll / GetDetail
=> Create slides controllers

controllers/members.js, controllers/news.js, migrations/20220701015704-create-members.js, models/members.js
Members model
Members migration
Members controller
=> add model, migration & controllers Members

app.js, controllers/members.js, routes/members.js
**Get information from all Members.**
Members endpoint: /members
=> Ot225-73/add/endpoint/all list members

app.js, controllers/members.js, controllers/news.js, migrations/20220701015704-create-members.js, models/members.js, routes/members.js
- Create a new member
-  Validate is not null and is of type string
- Members endpoint: POST:/members
=> Ot225-74/add/endpoint/add a new member

app.js, controllers/members.js, controllers/news.js, migrations/20220701015704-create-members.js, models/members.js, routes/members.js
- Delete member
- Validate that the Member exists
- Members endpoint: DELETE:/members/:id
=> Ot225 75/add/endpoint/delete member

controllers/testimony.js, migrations/20220701233015-create-testimonials.js, models/testimonials.js, routes/testimony.js
Eliminación de testimonio y corrección en error de tipeo en el modelo de testimonio
=> Feature/ot225 71/eliminar testimonio

controllers/news.js
=> Added pagination to news getAll controller

migrations/20220705195505-create-members.js, models/members.js
- Add Migration for Members
- Add Model for Members
- Add base controller for Members
=> Members model

migrations/20220705203036-create-testimonials.js, models/testimonials.js
-Added migration for Testimonials
-Added model for Testimonials
-Added base controller for Testimonials
=> Added Controller, model and migration for Testimonials

README.md, app.js, controllers/users.js, models/user.js, routes/auth.js, seeders/20201109013159-create-demo-user.js, utils/express-validator.js, utils/jwt.js
- add endpoints: login & register wirh JWT
- add jwt for create token & verify if token header exists
- add endpoint to validate if exists an user authenticated
- add seeder for populate users table & readme with users credentials
=> Logic for authenticate users

controllers/categories.js, models/members.js, routes/members.js
- Add swagger documentation to members (CRUD)
=> ot225-96/add swagger documentation to Members

controllers/categories.js, controllers/users.js, middlewares/auth.js, package-lock.json, package.json, routes/members.js, utils/jwt.js
- Add middleware verifyRole
- update JWTgenerator function
=> ot225-27/add/middleware/verifyRole

controllers/users.js, utils/nodemailer.js, utils/template-mail.html
- Add util for send email (nodemailer) and template html
- Add function to send email after register
=> Add util for send email after register

config/config.js, controllers/users.js, models/index.js, test/auth.test.js, utils/sendgrid.js
=> User auth tests

test/testimonies.js
-Added tests for GET, POST, PUT and DELETE routes of /testimonies
=> Added testimonies test

controllers/categories.js, controllers/members.js, controllers/news.js, package-lock.json, package.json, test/members.js, test/news.js
hice el testeo con Mocha y Chai, agregue el error 404 en el update de miembros.
=> Feature/ot225 96/test members
